build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage-log'
                coverage:
                    file: 'coverage-log'
                    format: 'clover'